#!/bin/bash

# Конфиг CAVA "на лету"
config_file="/tmp/eww_cava_config"
echo "
[general]
bars = 8
[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 7
[color]
disable_colors = 1
" > $config_file

# Запускаем CAVA и обрабатываем вывод через sed (самый быстрый способ)
# Мы убираем ; в конце и заменяем цифры 0-7 на символы блоков
    cava -p $config_file | stdbuf -oL sed -u '
        s/;//g;
        s/0/_/g;
        s/1/▂/g;
        s/2/▃/g;
        s/3/▄/g;
        s/4/▅/g;
        s/5/▆/g;
        s/6/▇/g;
        s/7/█/g;
    '
    
