max-gamma = 150

profile {
    time = 9:00
    identity = true
}

profile {
<<<<<<< HEAD
<<<<<<< HEAD
    time = 18:15
=======
    time = 20:30
>>>>>>> 9d211cf (reinitialized repo)
=======
    time = 20:30
=======
<<<<<<< HEAD
    time = 18:15
=======
    time = 20:30
>>>>>>> 9d211cf (reinitialized repo)
>>>>>>> fca83c1 (reinitialized repo)
>>>>>>> 35089f2 (fixed pull issues)
    temperature = 2500
    gamma = 0.6
}
