$font1 = JetBrainsMono Nerd Font Propo
$font2 = Neucha

general {
	hide_cursor = false
}

animations {
	animations = true

  	bezier = easeOutCubic, 0.215, 0.61, 0.355, 1
	bezier = easeInOutCubic, 0.65, 0, 0.35, 1	
	bezier = easeInOutQuad, 0.45, 0, 0.55, 1

   	animation = fadeIn, 1, 10, easeInOutCubic
   	animation = fadeOut, 1, 7, easeInOutQuad
	animation = inputFieldFade, 1, 9, easeOutCubic
}

background {
	monitor = eDP-1
   	path = ~/media/wallps/mpvpaper_themes/vagabond.png
   	color = rgba(25, 20, 20, 1.0)
	blur_passes = 1
    blur_size = 1
}

image {
	monitor = eDP-1
	path = ~/.config/hypr/brook.jpg
	size = 210
	border_size = 2

	halign = left
	valign = top 
	position = 40, -40
}

input-field {
    monitor = eDP-1

    size = 20%, 5%
    rounding = 13

    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill
    
    outer_color = rgba(ffffffff) 
    check_color = rgba(464646cc) rgba(7e7e7ecc) 100deg
    fail_color = rgba(000000ee) rgba(000000ee) 40deg
    capslock_color = rgba(464646cc)

    font_family = $font2
    font_color = rgb(143, 143, 143)
    placeholder_text = Вещай...

    fail_text = Ты точно то жмал?
    fail_color = rgb(143, 143, 143)

    fade_on_empty = false

    position = 43, 80
    halign = left
    valign = bottom
}

#shape nearby image
shape {
    monitor = eDP-1
    size = 480, 208
    color = rgba(0, 0, 0, 0.0) # no fill
    rounding = 0 # circle
    border_size = 3
    border_color = rgba(180, 180, 180, 0.8)    

    position = 140, -40
    halign = left
    valign = top
}

#shape under image, connect like 
shape {
	monitor = eDP-1

	size = 3,78%
	color = rgba(255, 255, 255, 1.0)
	
	position = 40, -150
	halign = left 
	valign = top
}

#Time
label {
    monitor = eDP-1
    text = $TIME # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 40
    font_family = $font2

    position = 510, -50
    halign = left
    valign = top
}

#layout
label {
    monitor = eDP-1
    text = $LAYOUT[en,ru]
    
    font_family = $font2
    font_size = 24
    onclick = hyprctl switchxkblayout all next

    position = 435, 87
    halign = left
    valign = bottom
}

#Text in shape
label {
	monitor = eDP-1
	
	text = REDLINE
	color = rgba(245, 73, 39, 1)       

	font_family = Thunderman Italic
	font_size = 39

	text_align = center

	position = 300, -130
	halign = left
	valign = top
}
