source = ~/.cache/wal/colors-hyprland.conf

background = rgb($color0)

base = rgb($foreground)
alternate_base = rgb($color1)

text = rgb($color1)
bright_text = rgb($color3)

accent_color = ($color9)

font_family = Thunderman
font_family_monospace = JetBrainsMono Nerd Font Propo

h1_size = 32
h2_size = 20

icon_theme = Papirus-Dark
