--# Please note not all available settings / options are set here.
----# For a full list, see the wiki
--source = ~/.config/hypr/configs/monitors.conf
--source = ~/.config/hypr/configs/variables.conf
--source = ~/.config/hypr/configs/autostart.conf
--source = ~/.config/hypr/configs/envvariables.conf
--source = ~/.config/hypr/configs/permissions.conf
--source = ~/.config/hypr/configs/aesthethic.conf
--source = ~/.config/hypr/configs/animations.conf
--source = ~/.config/hypr/configs/input.conf
--source = ~/.config/hypr/configs/binds.conf
--source = ~/.config/hypr/configs/window-spaceRules.conf
--
hl.config({ autogenerated = false }) 

require("configs/variables")
require("configs/envvariables")
require("configs/monitors")
require("configs/input")
require("configs/autostart")
require("configs/binds")
require("configs/window-spaceRules")
require("configs/permissions")
require("configs/aesthethic")

