#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox

## Used hyprshade earlier, saved it just for save
#exec-once = exec-once = dbus-update-activation-environment --systemd HYPRLAND_INSTANCE_SIGNATURE
#exec = hyprshade auto

exec-once = mpv ~/Media/start-sounds/dxnteryan-re-valution-mind-and-freedom-skysoundcc_WErsvVYM.mp3 --volume=50 --no-terminal --no-video &
exec-once = swww-daemon 

exec-once = swww img $wallpaperfir --transition-fps 144 --transition-duration 1 --transition-type fade --transition-bezier .07,.82,.17,1 &&  walrs -q -i $wallpaperfir -b 20 -s 120 -W
exec-once = vicinae server

exec-once = hyprlauncher -d
exec-once = hypridle &
exec-once = hyprsunset &

exec-once = ~/.local/bin/low_battery_notify.sh

