#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/
env = PATH,$PATH:/usr/bin

env = XCURSOR_THEME,Comix Cursor origin White
env = XCURSOR_SIZE,48

env = HYPRCURSOR_SIZE,24
env = GTK_THEME,Graphite-Dark:darker


