# Set programs that you use
$terminal = kitty 
$fileManager = $terminal -e ranger
$menu = wofi --show drun -b -a --term=$terminal -C ~/.cache/wal/colors.css

$wallpaperfir = ~/Media/Wallpapers/Solyanka/sonoshee.jpg
$startsound = 'mpv "$(find ~/Media/start-sounds -type f | shuf -n 1)" --volume=50 --no-terminal --no-video'
